# Generated by Django 3.0.5 on 2021-04-27 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_category_genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(2021, message='Введен некорректный год')),
        ),
    ]
